ALTER TABLE domaines ADD `dnssec` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE domaines ADD `dnssec_action` ENUM ('OK', 'CREATE') NOT NULL DEFAULT 'OK';
ALTER TABLE domaines ADD `ksk_algorithm` ENUM ('NSEC3RSASHA1', 'NSEC3DSA', 'RSASHA256', 'RSASHA512', 'ECDSAP256SHA256', 'ECDSAP384SHA384') DEFAULT NULL;
ALTER TABLE domaines ADD `ksk_keysize` INT DEFAULT NULL;
ALTER TABLE domaines ADD `zsk_algorithm` ENUM ('NSEC3RSASHA1', 'NSEC3DSA', 'RSASHA256', 'RSASHA512', 'ECDSAP256SHA256', 'ECDSAP384SHA384') DEFAULT NULL;
ALTER TABLE domaines add `zsk_keysize` INT DEFAULT NULL;
